version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "light-function"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dl7z18uegtry"
s3_prefix = "light-function"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
